version: '3'
services:
  keycloak_be_poc:
    container_name: keycloak_be_poc
    image: keycloak-be-poc:latest
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ../../.prod.env
    networks:
      - ace_network
    depends_on:
      - "keycloak_be_poc_mongodb"

  keycloak_be_poc_mongodb:
    container_name: keycloak_be_poc_mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - keycloak_be_poc_mongodb_volume:/data/db
    networks:
      - ace_network

networks:
  ace_network:
      driver: bridge

volumes:
  keycloak_be_poc_mongodb_volume:
